---
title: "Oxnard Data Cleaning and Cohort Grouping"
author: "Ryan Kinville"
date: "July 2018"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

```{r setup, include=FALSE}

library(tidyverse)
library(fs)
library(googlesheets)
library(readxl)
library(janitor)
library(cellranger)
library(visdat)
library(skimr)
library(naniar)

```


```{r, include=FALSE}


# 2014-2015

a14 <- gs_title("attendance 1415.csv") %>% gs_read() %>% clean_names()

res14 <- bind_cols((gs_read(gs_title("CAASPP14-15.xlsx"), range = cell_cols(1:10)) %>% remove_empty(which = "rows")),
            (gs_read(gs_title("CAASPP14-15.xlsx"), range = cell_cols(11:13), skip = 2) %>% remove_empty(which = "rows"))) %>% 
  clean_names() %>% 
  rename("local_stu_id" = "student_id")

both14 <- full_join(a14,res14,by = "local_stu_id") %>% mutate(school_year = "14-15")


# 2015-2016

a15 <- gs_title("attendance 1516.csv") %>% gs_read() %>% clean_names()

res15 <- bind_cols((gs_read(gs_title("CAASPP15-16.xlsx"), range = cell_cols(1:10)) %>% remove_empty(which = "rows")),
            (gs_read(gs_title("CAASPP15-16.xlsx"), range = cell_cols(11:13), skip = 2) %>% remove_empty(which = "rows"))) %>% 
  clean_names() %>% 
  rename("local_stu_id" = "student_id")

both15 <- full_join(a15,res15,by = "local_stu_id") %>% mutate(school_year = "15-16")


# 2016-2017

a16 <- gs_title("attendance 1617.csv") %>% gs_read() %>% clean_names()

res16 <- bind_cols((gs_read(gs_title("CAASPP16-17.xlsx"), range = cell_cols(1:10)) %>% remove_empty(which = "rows")),
            (gs_read(gs_title("CAASPP16-17.xlsx"), range = cell_cols(11:13), skip = 2) %>% remove_empty(which = "rows"))) %>% 
  clean_names() %>% 
  rename("local_stu_id" = "student_id")

both16 <- full_join(a16,res16,by = "local_stu_id") %>% mutate(school_year = "16-17")


# Long Data

long14to17 <- bind_rows(both14,both15,both16) %>%  replace_with_na(replace = list(language_fluency = "Unknown"))


# Alt Data - must have grade data

left14 <- left_join(res14,a14,by = "local_stu_id") %>% mutate(school_year = "14-15")
left15 <- left_join(res15,a15,by = "local_stu_id") %>% mutate(school_year = "15-16")
left16 <- left_join(res16,a16,by = "local_stu_id") %>% mutate(school_year = "16-17")
alt14to17 <- bind_rows(left14,left15,left16) %>% replace_with_na(replace = list(language_fluency = "Unknown"))

```

```{r, include=FALSE}

cohortitize <- function(x) {
  c1 <- alt14to17 %>%
    filter(school_year=="14-15" & grade==(9-x)) %>% 
    transmute(n = sum(!is.na(level)),
             n_basic_data = sum(!is.na(first_name)),
             n_test_scores = sum(!is.na(level)),
             n_attendance = sum(!is.na(unexc)),
             n_lang = sum(!is.na(language_fluency))) %>% 
    distinct() %>% 
    mutate(school_year = "14-15",
           grade = (9-x))
  c2 <- alt14to17 %>%
    filter(school_year=="15-16" & grade==(10-x)) %>% 
    transmute(n = sum(!is.na(level)),
             n_basic_data = sum(!is.na(first_name)),
             n_test_scores = sum(!is.na(level)),
             n_attendance = sum(!is.na(unexc)),
             n_lang = sum(!is.na(language_fluency))) %>% 
    distinct() %>% 
    mutate(school_year = "15-16",
           grade = (10-x))
  c3 <- alt14to17 %>%
    filter(school_year=="16-17" & grade==(11-x)) %>% 
    transmute(n = sum(!is.na(level)),
             n_basic_data = sum(!is.na(first_name)),
             n_test_scores = sum(!is.na(level)),
             n_attendance = sum(!is.na(unexc)),
             n_lang = sum(!is.na(language_fluency))) %>% 
    distinct() %>% 
    mutate(school_year = "16-17",
           grade = (11-x))
  c4 <- bind_rows(c1,c2,c3) %>% 
    mutate(cohort = x)
  answer <- c4[c(8,6:7,1:5)]
  return(answer)
}

c1 <- cohortitize(1)
c2 <- cohortitize(2)
c3 <- cohortitize(3)
c4 <- cohortitize(4)
c5 <- cohortitize(5)
c6 <- cohortitize(6)
c7 <- cohortitize(7)
c8 <- cohortitize(8)
c9 <- cohortitize(9)
c10 <- cohortitize(10)

cohortscompiled <- bind_rows(c1,c2,c3,c4,c5,c6,c7,c8,c9,c10)

write_rds(cohortscompiled, path_expand("~/Desktop/cohorts.rds"))

```


```{r}

cohortscompiled

```


