---
title: "Oxnard Data Name Matching"
author: "Ryan Kinville"
date: "July 2018"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

```{r}

library(tidyverse)
library(fs)
library(googlesheets)
library(readxl)
library(janitor)
library(cellranger)
library(visdat)
library(skimr)
library(naniar)
library(knitr)
library(readr)
library(lubridate)

```


```{r}

# Upload First5 Data

serv <- gs_url("https://docs.google.com/spreadsheets/d/1P-6nDO0J3KdUBaF1MzWv5rtIIn5WAUwCWZoUHKn-Qxs/edit#gid=1694710406") %>% gs_read(., range = cell_cols(1:5))

distinctrowstotal <- read_rds(path_expand("~/Destop/distinctrowstotal.rds"))

# Join

joined <- left_join(distinctrowstotal,serv,by="ClientID") %>% 
  clean_names() %>% 
  mutate(mname = toupper(paste(last_name , first_name)),
         dob = parse_date_time(mdy(dob), "ymd"))

# Upload Oxnard Data

oxnard <- read_rds(path_expand("~/Desktop/oxnard.rds")) %>% 
  mutate(mname = toupper(paste(last_name , first_name)),
         dob = parse_date_time(birth_date, "ymd"))

# Join

namematch <- left_join(oxnard,joined,by = c("mname", "dob"))

# Get rid of trash dumb duplicates

distnames <- namematch %>% 
  distinct(mname,dob, .keep_all = TRUE)

vis_dat(distnames, warn_large_data = F)
  

```
```{r results = 'asis'}

kable(nrow(distnames))

```
